version: "3.9"
services:

  jump:
    build:
      context: ./
      dockerfile: ./ExposedJumpHost/Dockerfile
    environment:
      - TAG=JUMPHOST
    networks:
      - ansible
    ports:
      - "22009:22"
    volumes:
      - secrets:/home/tunnel/.ssh

  ansi_main:
    build:
      context: ./
      dockerfile: ./main/Dockerfile
    environment:
      - TAG=MAIN
    networks:
      - ansible
    ports:
      - "22009:22"
    volumes:
     - secrets:/home/ansible/.ssh

  ansi_fe1:
    build:
      context: ./
      dockerfile: ./sub/Dockerfile
    environment:
      - TAG=FE_1
    networks:
      - ansible
    volumes:
      - secrets:/home/ansible/.ssh
  ansi_fe2:
    build:
      context: ./
      dockerfile: ./sub/Dockerfile
    environment:
      - TAG=FE_2
    networks:
      - ansible
    volumes:
      - secrets:/home/ansible/.ssh
  ansi_be1:
    build:
      context: ./
      dockerfile: ./sub/Dockerfile
    environment:
      - TAG=BE_1
    networks:
      - ansible
    volumes:
      - secrets:/home/ansible/.ssh
  ansi_be2:
    build:
      context: ./
      dockerfile: ./sub/Dockerfile
    environment:
      - TAG=BE_2
    networks:
      - ansible
    volumes:
      - secrets:/home/ansible/.ssh

networks:
  ansible:
    internal: true

volumes:
  secrets:
